kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        valueFrom:
          configMapkeyRef:
            name: nginx-config
            key: course
      - name: duration
        value: "120hr"